FROM rocker/rstudio:4.3.1

# Install system dependencies for R packages
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libgit2-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    libpng-dev \
    libtiff5-dev \
    libjpeg-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    git \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

# Install CRAN packages
RUN R -e "install.packages(c( \
  'tidyverse', \
  'jsonlite', \
  'ggplot2', \
  'pheatmap', \
  'cowplot', \
  'RColorBrewer', \
  'msigdbr' \
), repos='https://cloud.r-project.org/')"

# Install Bioconductor manager
RUN R -e "install.packages('BiocManager', repos='https://cloud.r-project.org/')"

# Install Bioconductor packages
RUN R -e "BiocManager::install(c( \
  'DESeq2', \
  'edgeR', \
  'limma', \
  'apeglm', \
  'tximport', \
  'biomaRt', \
  'GEOquery', \
  'org.Hs.eg.db', \
  'clusterProfiler', \
  'fgsea', \
  'GSEABase', \
  'ComplexHeatmap' \
), ask=FALSE, update=TRUE)"

WORKDIR /home/rstudio/project

EXPOSE 8787
